version: "3.9"

services:
  mockserver:
    image: mockserver/mockserver:5.15.0
    container_name: mockserver
    ports:
      - "1080:1080"
    environment:
      MOCKSERVER_LOG_LEVEL: DEBUG
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/mockserver.json
    volumes:
      - ./mockserver/mockserver.json:/config/mockserver.json